---
deployment:
  tasks:
    - export DEPLOYPATH=/home/timetvmcorg/public_html
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/mkdir -p "$DEPLOYPATH/app" "$DEPLOYPATH/config" "$DEPLOYPATH/storage/logs"
    - /bin/cp -R app/. "$DEPLOYPATH/app/"
    - /bin/cp -R config/. "$DEPLOYPATH/config/"
    - /bin/cp bootstrap.php "$DEPLOYPATH/bootstrap.php"
    - /bin/cp -R public/. "$DEPLOYPATH/"